#!/bin/bash

str=$(sudo dpkg -s python-qt4 | grep -oh "installed")
reset
if [ "$str" == "installed" ]; then
    echo "> Python-qt4 installed"
else
    echo "> Wait we need lib :P Python-qt4"
    sudo apt-get install python-qt4
fi

echo "> Compile server ..."
g++ server/main.cpp server/client_handle.cpp server/editor.cpp -o server/server -Wall -Wextra -std=c++11 -lpthread
if [ $? -eq 0 ]; then
    echo "> Server build"
else
    echo "> Server build failed"
    exit 1
fi

echo "> Compile client ..."
g++ client/main.cpp -o client/client -Wall -Wextra -std=c++11 -lpthread
if [ $? -eq 0 ]; then
    echo "> Client build"
else
    echo "> Client build failed"
    exit 2
fi
