#!/bin/bash

echo "> Compile server ..."
g++ server/main.cpp server/client_handle_editor.cpp server/client_handle_activ.cpp server/control_client.cpp server/control_clientACA.cpp server/accept_connections_ed.cpp server/accept_connections_activ.cpp -o server/server -Wall -Wextra -std=c++11 -lpthread -g
if [ $? -eq 0 ]; then
    echo "> Server build"
else
    echo "> Server build failed"
    exit 1
fi

echo "> Compile client ..."
g++ client/main.cpp client/manage_editor.cpp client/manage_activ.cpp -o client/client -Wall -Wextra -std=c++11 -lpthread -g
if [ $? -eq 0 ]; then
    echo "> Client build"
else
    echo "> Client build failed"
    exit 2
fi
